<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="AGS-CHP-107" failures="1" tests="1" name="Default test" time="102.236" errors="0" timestamp="2020-06-02T22:48:22 IST">
  <testcase classname="ro.altom.altunitytesterexample.CheckAltUnityTesterConnectivity" name="main" time="102.179">
    <failure type="ro.altom.altunitytester.altUnityTesterExceptions.NotFoundException" message="error:notFound">
      <![CDATA[ro.altom.altunitytester.altUnityTesterExceptions.NotFoundException: error:notFound
at ro.altom.altunitytester.Commands.AltBaseCommand.handleErrors(AltBaseCommand.java:87)
at ro.altom.altunitytester.Commands.AltCommandReturningAltObjects.ReceiveAltUnityObject(AltCommandReturningAltObjects.java:25)
at ro.altom.altunitytester.Commands.OldFindObject.AltFindElement.Execute(AltFindElement.java:17)
at ro.altom.altunitytester.AltUnityDriver.findElement(AltUnityDriver.java:463)
at ro.altom.altunitytester.AltUnityDriver.findElement(AltUnityDriver.java:470)
at ro.altom.altunitytester.AltUnityDriver.findElement(AltUnityDriver.java:485)
at ro.altom.altunitytesterexample.CheckAltUnityTesterConnectivity.main(CheckAltUnityTesterConnectivity.java:64)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- main -->
</testsuite> <!-- Default test -->
